### ISSUE TITLE
Bakground for widgets is yellow

### ISSUE THREAD

**Issue by brett-mobsby** [dodgydesigns/Buffetiser#15]
![Screen Shot 2021-02-20 at 10 36 55 am](https://user-images.githubusercontent.com/20390789/108580716-b7f45180-7367-11eb-9ad0-23ce0189987e.png)

**Comment by dodgydesigns** [comment]
Hmmm. Yucki

**Comment by dodgydesigns** [comment]
Fixed with styling.
