### ISSUE TITLE
usdToAudConversion.txt is not updated after retrieving new rate

### ISSUE THREAD

**Issue by brett-mobsby** [dodgydesigns/Buffetiser#17]
After the current rate is retrieved, it gets used in calculations but it is not saved for next time.
If the file does not exist on startup, an exception is thrown.
A get is invoked to retrieve the rate for each crypto currency when it's really only required once for all.
Rate should be retrieved on startup if one is not already available and updated before getting live data.

**Comment by dodgydesigns** [comment]
currencyConversion is now a key in the config.csv file. Lots of this stuff has been moved to model.py. Just need to read current conversion (based on user's currency e.g. AUD, USD) and when a live update is invoked, write the new conversion factor to file.

**Comment by dodgydesigns** [comment]
Currency conversion is saved to config now.
