### ISSUE TITLE
Allow crypto (and shares) to be entered as either price or cost

### ISSUE THREAD

**Issue by brett-mobsby** [dodgydesigns/Buffetiser#6]
Particularly if you are paying fees or commision on a purchase, it would be easier to specify the total amount rather than calculating how much you payed per share.

Was thinking something like this to allow either:
crypto,ETH,Ethereum,0.00407823,2452.04,
or
crypto,ETH,Ethereum,0.00407823,,10

**Comment by brett-mobsby** [comment]
It almost looks like you intended to handle crypto differently to shares. You've implemented methods on class Crypto but they are the same and the super.
Do we just make it so that crypto specifies the total cost in $

**Comment by dodgydesigns** [comment]
I like the idea. I might put a rule in that if a total purchase cost is put in the config file, it uses that otherwise it used costPrice*unitsHeld. I don't want to have to put a button on for it.

What do you think?

**Comment by dodgydesigns** [comment]
If I buy $1000 + fee$4.95 @USD40000 of BTC and the
   I buy $2000 + fee$4.95 @USD52000 of BTC

I should be able to enter both transactions in as separate lines in the config and have Buffetiser work out what's what.

Happy you suggested this? 🤣
